os: linux
dist: focal
language: python

jobs:
  include:
    - name: Linux | s390x | Python 3.9
      python: 3.9
      services: docker
      arch: s390x
      env: PYTHON=python

install:
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then docker run --rm --privileged docker.io/tonistiigi/binfmt:latest --install all; fi
- $PYTHON -m pip install -U pip
- $PYTHON -m pip install -e ".[dev]" pytest-custom-exit-code

script: |
  # travis_wait disable the output while waiting
  # use the same kind of tricks as in multibuild
  (while true; do echo "travis_keep_alive"; sleep 300; done) &
  SPINNER_PID=$!
  disown
  result=0
  $PYTHON ./bin/run_tests.py --num-processes 2 || result=1
  kill -9 ${SPINNER_PID}
  test ${result} -eq 0
